version: '3'

services:

  siwe-backend:
    image: siwe-backend
    container_name: siwe-backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=postgres
      - DB_HOST=siwe-postgres
      - DB_NAME=siwe
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - SESSION_SECRET=eaaafa09-9ae5-47a9-9a16-69cec0a3db1c
    depends_on:
      siwe-postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  siwe-postgres:
    image: postgres:15-alpine
    container_name: siwe-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: siwe
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
