version: '3'

services:

  siwe-postgres:
    image: postgres:15-alpine
    container_name: siwe-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: siwe
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5436:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
